apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather
  ports:
    - name : HTTP      
      port: 80
      protocol: TCP
      targetPort: 7070 # 어플리케이션이 노출하는 포트로 변경해야 합니다.