apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-application
  template:
    metadata:
      labels:
        app: weather-application
    spec:
      containers:
        - name: weather-application
          image: weather:latest
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070 # 어플리케이션이 노출하는 포트로 변경해야 합니다.
